/*
 * SomnoTrace - SomnoStage model key halves (injected, gitignored)
 * Copyright (C) 2026 Ilya Kruchinin <https://github.com/ilyakruchinin>
 *
 * This file is part of SomnoTrace.
 *
 * SomnoTrace is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * SomnoTrace is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * ADDITIONAL TERM (GPLv3 Section 7(b)): Redistributions must preserve the
 * attribution "Based on SomnoTrace, originally created by Ilya Kruchinin
 * (https://github.com/ilyakruchinin)." See the NOTICE file for details.
 */

/* key_a.inc / key_b.inc are generated by scripts/inject-model.sh (dev) or by
 * the release pipeline (official builds) and are gitignored.  Splitting the
 * XOR halves across separate objects keeps a contiguous 32-byte key out of
 * the binary image; the mask is fixed per release so the halves look like
 * ordinary constant data to bindiff. */

#include "somno_ml_internal.h"

static const uint8_t s_key_a[32] = {
#include "key_a.inc"
};

static const uint8_t s_key_b[32] = {
#include "key_b.inc"
};

void somno_ml_reconstruct_key(uint8_t out[32])
{
    for (int i = 0; i < 32; i++)
        out[i] = s_key_a[i] ^ s_key_b[i];
}
